#!/bin/bash

GTKDIALOG=gtkdialog
export MAIN_DIALOG='

<window title="Super Cipher" resizable="true" width-request="250" height-request="300">
<vbox>
<notebook labels="Caesar | Vigenere">
<vbox>
	<hbox space-fill="true">
	      <text> 
		<label>key</label>
	      </text>
	</hbox>
	<hbox space-fill="true">
	      <spinbutton range-min="0" range-max="26" range-value="1">
                <variable>k</variable>
              </spinbutton>
	</hbox>
	<hbox space-fill="true">
	      <text><label>messasge</label></text>
	</hbox>
	<hbox space-fill="true">
	      <entry>
		<variable>p</variable>
	      </entry>
	 </hbox>

	 <hbox space-fill="true">
		<button>
		 <label>Cipher</label>
		 <action>./cipher $k $p</action>
		</button>
	 </hbox>
</vbox>
<vbox>
      <hbox space-fill="true">
        <text><label>key</label></text>
      </hbox>
      <hbox space-fill="true">
        <entry>
          <variable>vk</variable>
        </entry>
      </hbox>
      <hbox space-fill="true">
        <text><label>message</label></text>
      </hbox>
     <hbox space-fill="true">
        <entry>
          <variable>vp</variable>
        </entry>
     </hbox>
</vbox>
</notebook>
   <hbox>
     <button ok></button>
   </hbox>
</vbox>
</window>
'

case $1 in
     	-d | --dump) echo "$MAIN_DIALOG" ;;
	*) $GTKDIALOG --program=MAIN_DIALOG --center ;;
esac
